In [1]:
print('hello')

hello


In [4]:
import numpy as np

# Array setup in numpy

In [15]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0,8.0,7.0],[60.0,5.0,4.0]])
print(b)

[[ 9.  8.  7.]
 [60.  5.  4.]]


In [10]:
# get Dimension

In [11]:
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [16]:
# get type
a.dtype

dtype('int16')

In [17]:
# get Size
a.itemsize

2

In [18]:
b.itemsize

8

In [19]:
a.nbytes

6

In [20]:
b.nbytes

48

In [21]:
b.dtype

dtype('float64')

### Accessing/Changing specific elements ,row, column, etc


In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# Get a specific element [r, c]
a[1,5]

13

In [24]:
# Get a Specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
a[:,2]

array([ 3, 10])

In [26]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:]

array([2, 3, 4, 5, 6, 7])

In [36]:
a[0, 1:6: 2]

array([2, 4, 6])

In [37]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]
