In [1]:
print('hello')

hello


In [4]:
import numpy as np

# Array setup in numpy

In [15]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0,8.0,7.0],[60.0,5.0,4.0]])
print(b)

[[ 9.  8.  7.]
 [60.  5.  4.]]


In [10]:
# get Dimension

In [11]:
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [16]:
# get type
a.dtype

dtype('int16')

In [17]:
# get Size
a.itemsize

2

In [18]:
b.itemsize

8

In [19]:
a.nbytes

6

In [20]:
b.nbytes

48

In [21]:
b.dtype

dtype('float64')

### Accessing/Changing specific elements ,row, column, etc


In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# Get a specific element [r, c]
a[1,5]

13

In [24]:
# Get a Specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
a[:,2]

array([ 3, 10])

In [26]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:]

array([2, 3, 4, 5, 6, 7])

In [36]:
a[0, 1:6: 2]

array([2, 4, 6])

In [37]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


In [39]:
a[0:2,6] =45
print(a)

[[ 1  2  5  4  5  6 45]
 [ 8  9  5 11 12 13 45]]


In [40]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
# Get Specific element
b[0,1,1]

4

In [42]:
b[:1:]

array([[[1, 2],
        [3, 4]]])

In [43]:
b[:0:]

array([], shape=(0, 2, 2), dtype=int32)

## Initializing Different Types of Arrays

In [45]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:

np.zeros((3,5),dtype="int32")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [49]:

np.ones((2,3,4,5),dtype="int16")

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int16)

In [50]:
# get other number array
np.full((2,2),99,dtype="int16")

array([[99, 99],
       [99, 99]], dtype=int16)

In [52]:
# get other number array with other arrar shape
np.full(a.shape,4,dtype='int16')

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]], dtype=int16)

In [53]:
np.full_like(a,4,dtype='int16')

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]], dtype=int16)

In [54]:
get random decimal
np.random.rand(5,6)

array([[0.97848695, 0.61758541, 0.804484  , 0.84083221, 0.68302063,
        0.94943205],
       [0.5823492 , 0.78588758, 0.55726716, 0.96324868, 0.15243648,
        0.11080077],
       [0.2369134 , 0.76004748, 0.86845734, 0.38201334, 0.30308595,
        0.37198729],
       [0.98399939, 0.79912393, 0.2766598 , 0.65218684, 0.87043658,
        0.33407328],
       [0.64307035, 0.73391046, 0.46069198, 0.05950479, 0.33413998,
        0.02111948]])

In [58]:
# the indentify matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
# repeat array
arr = np.array([[1,2,3]])
t = np.repeat(arr,3,axis=0)
print(t)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [68]:
o = np.ones((5,5))
print(o)
p = np.zeros((3,3))
print(p)
o[1:4,1:4] = p
print(o)
p[1,1] = 9
o[1:-1,1:-1]= p
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Imp *

In [73]:
a =np.array([1,2,3])
print(a)
b=a
# b[0]= 100
print(a)
print(b)
c = a.copy()
c[0]=100
print(a,c)

[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3] [100   2   3]


# maths

In [76]:
 a= np.array([1,2,3])
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[1 2 3]
[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]


# Linear Algebra

In [79]:
a = np.ones((2,3))
b = np.full((3,2),4)
print(np.matmul(a,b))

[[12. 12.]
 [12. 12.]]


In [81]:
c = np.identity(3)

In [82]:
# determinent
np.linalg.det(c)

1.0